table Carpetas_Existentes
	lineageTag: 08456295-5592-4d6f-88f3-942b5111b649

	column SALIDA_AJUSTADA
		dataType: dateTime
		formatString: General Date
		lineageTag: b4cfd6ca-00f1-4e15-a251-7be6abae2ac5
		summarizeBy: none
		sourceColumn: SALIDA_AJUSTADA

		variation Variation
			isDefault
			relationship: 94c887e3-a4a8-4c6f-a958-73f609a2d22f
			defaultHierarchy: LocalDateTable_189eff17-38da-4c1a-9910-e4c351fd79db.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column PURCHID
		dataType: string
		lineageTag: 4b3ffa1f-c406-4c51-bceb-0f449ee54f40
		summarizeBy: none
		sourceColumn: PURCHID

		annotation SummarizationSetBy = Automatic

	column 'DOCUMENTATION.FECHA_BL'
		dataType: dateTime
		formatString: General Date
		lineageTag: 4a0e84b5-04da-4c64-9c10-f2643462b416
		summarizeBy: none
		sourceColumn: DOCUMENTATION.FECHA_BL

		variation Variation
			isDefault
			relationship: 7c00198c-1c23-4f34-9dfe-f322546e4151
			defaultHierarchy: LocalDateTable_ed6da6d1-bf1f-41c0-950e-725959ec60ba.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'DOCUMENTATION.APROB_CERTIF_ORIGEN'
		dataType: dateTime
		formatString: General Date
		lineageTag: 151e51bc-421f-4346-99e8-ff72d68e279f
		summarizeBy: none
		sourceColumn: DOCUMENTATION.APROB_CERTIF_ORIGEN

		variation Variation
			isDefault
			relationship: 4812b7ce-0920-44d3-ae09-28b411ef3ab5
			defaultHierarchy: LocalDateTable_6fe27e4a-ba84-45cf-bb49-54f5812a9136.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column OC_EXISTENTES
		dataType: string
		lineageTag: 72dad3e2-0dad-40f0-a938-ce0ec5ced71f
		summarizeBy: none
		sourceColumn: OC_EXISTENTES

		annotation SummarizationSetBy = Automatic

	column BL_EXISTENTE
		dataType: string
		lineageTag: c9c33b98-a2c7-4cef-a6d4-e5376051b46f
		summarizeBy: none
		sourceColumn: BL_EXISTENTE

		annotation SummarizationSetBy = Automatic

	column EURO_PO_EXISTENTE
		dataType: string
		lineageTag: 479c646a-3b44-42ff-8359-6064c46302fa
		summarizeBy: none
		sourceColumn: EURO_PO_EXISTENTE

		annotation SummarizationSetBy = Automatic

	partition Carpetas_Existentes = m
		mode: import
		source =
				let
				    Source = Sql.Database("SJODB002", "GIAX2012_PROD", [MultiSubnetFailover=true]),
				    dbo_PURCHASE_PBI = Source{[Schema="dbo",Item="PURCHASE_PBI"]}[Data],
				    #"Added Custom" = Table.AddColumn(dbo_PURCHASE_PBI, "Artículo", each "("&[ITEMID]&")"&" "&[PRODUCTNAME]),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "KEY", each [DATAAREAID]&[ORDERACCOUNT]),
				    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "KEY_GEN", each [DATAAREAID]&[ITEMID]),
				    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "KEY_1", each [DATAAREAID] & Text.From([NUMERO_CONTRATO])),
				    #"Personalizada agregada" = Table.AddColumn(#"Added Custom3", "KEY_RECEP", each [PURCHID] & [UNIDAD]),
				    #"Columna duplicada" = Table.DuplicateColumn(#"Personalizada agregada", "PURCHID", "PURCHID - Copia"),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Columna duplicada","OC-00","",Replacer.ReplaceText,{"PURCHID - Copia"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","OC_00","",Replacer.ReplaceText,{"PURCHID - Copia"}),
				    #"Added Custom4" = Table.AddColumn(#"Valor reemplazado1", "Vencimiento Días Libres", each if [LLEGADA_PAIS] = null or [DIAS_LIBRES] = null then null else Date.AddDays([LLEGADA_PAIS], [DIAS_LIBRES])),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom4",{{"Vencimiento Días Libres", type date}}),
				    #"Added Index" = Table.AddIndexColumn(#"Changed Type", "Index", 1, 1, Int64.Type),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Index",{{"LLEGADA_DOC_ORIGEN", type date}}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Changed Type1",{"SALIDA_AJUSTADA", "PURCHID"}),
				    #"Merged Queries" = Table.NestedJoin(#"Removed Other Columns1", {"PURCHID"}, DOCUMENTATION, {"PURCHID"}, "DOCUMENTATION", JoinKind.LeftOuter),
				    #"Expanded DOCUMENTATION" = Table.ExpandTableColumn(#"Merged Queries", "DOCUMENTATION", {"FECHA_BL", "APROB_CERTIF_ORIGEN"}, {"DOCUMENTATION.FECHA_BL", "DOCUMENTATION.APROB_CERTIF_ORIGEN"}),
				    #"Added Custom5" = Table.AddColumn(#"Expanded DOCUMENTATION", "OC_EXISTENTES", each if [PURCHID] = "OC-00166300" then "Sí" else "No"),
				    #"Added Custom6" = Table.AddColumn(#"Added Custom5", "BL_EXISTENTE", each if [PURCHID] = "OC-00166300" then "Sí" else "No"),
				    #"Added Custom7" = Table.AddColumn(#"Added Custom6", "EURO_PO_EXISTENTE", each if [PURCHID] = "OC-00166300" then "Sí" else "No"),
				    #"Replaced Value" = Table.ReplaceValue(#"Added Custom7","No","Sí",Replacer.ReplaceText,{"OC_EXISTENTES"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","No","Sí",Replacer.ReplaceText,{"BL_EXISTENTE"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","No ","Sí",Replacer.ReplaceText,{"EURO_PO_EXISTENTE"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","No","Sí",Replacer.ReplaceText,{"EURO_PO_EXISTENTE"})
				in
				    #"Replaced Value3"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

