table Consulta1
	lineageTag: a5bf2628-5ef6-460c-8a13-8d114d4837e9

	column DATAAREAID
		dataType: string
		lineageTag: c4c29a88-8b97-47c8-a064-0e523f524a16
		summarizeBy: none
		sourceColumn: DATAAREAID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PO_MADRE
		dataType: string
		lineageTag: b5dc9932-2a75-4bd8-a2be-7ecc4bdc2672
		summarizeBy: none
		sourceColumn: PO_MADRE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PO_HIJA
		dataType: string
		lineageTag: f4ca6f6e-512a-4894-8c88-8dc926b1d705
		summarizeBy: none
		sourceColumn: PO_HIJA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TIPO
		dataType: string
		lineageTag: decde6ec-f113-4a45-902b-90215e3b8291
		summarizeBy: none
		sourceColumn: TIPO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ORDERACCOUNT
		dataType: string
		lineageTag: c9970510-53f6-499d-aaee-1569e6da0dd4
		summarizeBy: none
		sourceColumn: ORDERACCOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RECID
		dataType: int64
		formatString: 0
		lineageTag: db6383d4-7cf9-4d16-a932-0f2c12da4fcc
		summarizeBy: count
		sourceColumn: RECID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CREATEDDATETIME
		dataType: dateTime
		formatString: DD/MM/YY
		lineageTag: 0d922fc6-25d6-4107-ab7f-b752d8451572
		summarizeBy: none
		sourceColumn: CREATEDDATETIME

		variation Variation
			isDefault
			relationship: 2c37b44f-2ac1-4638-8417-403185ffab20
			defaultHierarchy: LocalDateTable_884a7c35-462a-446d-ad4d-75fff3147600.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column LINEAMOUNT
		dataType: double
		formatString: #,0
		lineageTag: 408049bf-380c-45ab-a4cf-17c8c8051f44
		summarizeBy: sum
		sourceColumn: LINEAMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column MONEDA
		dataType: string
		lineageTag: 9b8c5d0b-0c72-45ca-bd79-6e38737380c5
		summarizeBy: none
		sourceColumn: MONEDA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TIPOSERVICIO
		dataType: string
		lineageTag: c3892c2a-5fe9-4fa0-ae53-29aa3c7263bb
		summarizeBy: none
		sourceColumn: TIPOSERVICIO

		annotation SummarizationSetBy = Automatic

	column NOMBRE_PROVEEDOR =
			MAXX(
			    FILTER(
			        VENDOR_NAME,
			        UPPER(VENDOR_NAME[KEY]) = UPPER(Consulta1[DATAAREAID] & Consulta1[ORDERACCOUNT])
			    ),
			    VENDOR_NAME[CONCAT_NAME]
			)
		dataType: string
		lineageTag: f2bd4c92-a012-4e0f-8d94-04e66c8179ce

	hierarchy 'CREATEDDATETIME Hierarchy'
		lineageTag: 884e025e-6f40-4192-bf43-96835e82f1ce

		level 'Fecha Creación'
			lineageTag: af0e277e-0da4-4a26-8a03-e0f6c88b54db
			column: CREATEDDATETIME

		changedProperty = IsHidden

	partition Consulta1 = m
		mode: import
		source =
				let
				    Origen = Sql.Database("SJODB002", "GIAX2012_PROD", [Query="SELECT T1.DATAAREAID, T1.PURCHIDREFERENCE AS PO_MADRE, T1.PURCHID AS PO_HIJA, #(lf)T1.SERVICEID AS TIPO,T1.ORDERACCOUNT,T1.CREATEDDATETIME,T2.RECID, T2.LINEAMOUNT, T2.CURRENCYCODE AS MONEDA, T1.SERVICEID AS TIPOSERVICIO#(lf)FROM PURCHTABLE T1 LEFT OUTER JOIN#(lf)PURCHLINE T2 ON T2.PURCHID = T1.PURCHID AND T2.DATAAREAID = T1.DATAAREAID#(lf)WHERE T1.DATAAREAID = 'CMER' AND T1.PURCHIDREFERENCE <> ''", MultiSubnetFailover=true]),
				    #"DATAAREAID a mayúsculas" = Table.TransformColumns(Origen, {{"DATAAREAID", Text.Upper, type text}})
				in
				    #"DATAAREAID a mayúsculas"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

