table Dates2
	lineageTag: 7c100c4e-1010-4329-aeab-e229151c5acf

	column Semana
		dataType: string
		lineageTag: 2470fc4e-ca1d-4423-a6bd-2fd7785cabe1
		summarizeBy: none
		sourceColumn: Semana

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: bb1163f0-dbd5-4a01-94bc-a45f0f90b76d
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: 65ec3aac-ccc2-473a-bbce-abfc8c2f7090
			defaultHierarchy: LocalDateTable_cab84189-b5e7-4452-b042-eb19a112447a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Dates2 = m
		mode: import
		source =
				let
				    Source = Sql.Database("SJODB003", "GIAX2012_PROD", [Query="SELECT #(lf)#(tab)DATEADD(day, 1 - DATEPART(weekday, getdate()), getdate()) AS ""T"",#(lf)    DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()) - 1, 0) #(lf)    - CASE WHEN DATEPART(WEEKDAY, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 0)) = 1 #(lf)#(tab)THEN 0 ELSE DATEPART(WEEKDAY, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 0)) - 1 END AS ""T-1"",#(lf)#(tab)DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()) - 2, 0) #(lf)    - CASE WHEN DATEPART(WEEKDAY, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 0)) = 1 #(lf)#(tab)THEN 0 ELSE DATEPART(WEEKDAY, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 0)) - 1 END AS ""T-2"",#(lf)#(tab)DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()) - 3, 0) #(lf)    - CASE WHEN DATEPART(WEEKDAY, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 0)) = 1 #(lf)#(tab)THEN 0 ELSE DATEPART(WEEKDAY, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 0)) - 1 END AS ""T-3"",#(lf)#(tab)DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()) - 4, 0) #(lf)    - CASE WHEN DATEPART(WEEKDAY, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 0)) = 1 #(lf)#(tab)THEN 0 ELSE DATEPART(WEEKDAY, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 0)) - 1 END AS ""T-4"",#(lf)#(tab)DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()) - 5, 0) #(lf)    - CASE WHEN DATEPART(WEEKDAY, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 0)) = 1 #(lf)#(tab)THEN 0 ELSE DATEPART(WEEKDAY, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 0)) - 1 END AS ""T-5"",#(lf)#(tab)DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()) - 6, 0) #(lf)    - CASE WHEN DATEPART(WEEKDAY, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 0)) = 1 #(lf)#(tab)THEN 0 ELSE DATEPART(WEEKDAY, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 0)) - 1 END AS ""T-6"",#(lf)#(tab)DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()) - 7, 0) #(lf)    - CASE WHEN DATEPART(WEEKDAY, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 0)) = 1 #(lf)#(tab)THEN 0 ELSE DATEPART(WEEKDAY, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 0)) - 1 END AS ""T-7"",#(lf)#(tab)DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()) - 8, 0) #(lf)    - CASE WHEN DATEPART(WEEKDAY, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 0)) = 1 #(lf)#(tab)THEN 0 ELSE DATEPART(WEEKDAY, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 0)) - 1 END AS ""T-8"",#(lf)#(tab)DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()) - 9, 0) #(lf)    - CASE WHEN DATEPART(WEEKDAY, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 0)) = 1 #(lf)#(tab)THEN 0 ELSE DATEPART(WEEKDAY, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 0)) - 1 END AS ""T-9"",#(lf)#(tab)DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()) - 10, 0) #(lf)    - CASE WHEN DATEPART(WEEKDAY, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 0)) = 1 #(lf)#(tab)THEN 0 ELSE DATEPART(WEEKDAY, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 0)) - 1 END AS ""T-10"",#(lf)#(tab)DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()) - 11, 0) #(lf)    - CASE WHEN DATEPART(WEEKDAY, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 0)) = 1 #(lf)#(tab)THEN 0 ELSE DATEPART(WEEKDAY, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 0)) - 1 END AS ""T-11"",#(lf)#(tab)DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()) - 12, 0) #(lf)    - CASE WHEN DATEPART(WEEKDAY, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 0)) = 1 #(lf)#(tab)THEN 0 ELSE DATEPART(WEEKDAY, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 0)) - 1 END AS ""T-12""#(lf)", MultiSubnetFailover=true]),
				    #"Demoted Headers" = Table.DemoteHeaders(Source),
				    #"Changed Type" = Table.TransformColumnTypes(#"Demoted Headers",{{"Column1", type any}, {"Column2", type any}, {"Column3", type any}, {"Column4", type any}, {"Column5", type any}, {"Column6", type any}, {"Column7", type any}, {"Column8", type any}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}, {"Column13", type any}}),
				    #"Transposed Table" = Table.Transpose(#"Changed Type"),
				    #"Renamed Columns" = Table.RenameColumns(#"Transposed Table",{{"Column1", "Semana"}, {"Column2", "Fecha"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"Fecha", type date}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

