table Sales
	lineageTag: 253f62cb-e8e6-4d55-8e3a-9601faa2ae11

	measure CANT = SUMX(UNIDADES, SUM(SALES[CANTIDAD]) / Unidades[Und X Cajas])
		lineageTag: 44c07d64-299a-4b15-9839-5549688bf519

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure QTY = ```
			
			SUMX(
			    SALES, 
			    IF(
			        ISNUMBER(SALES[Fact]) && SALES[Fact] <> 0, 
			        DIVIDE(SALES[CANTIDAD], SALES[Fact], 0), 
			        0
			    )
			)
			```
		formatString: #,0
		lineageTag: 6b6cbac5-6993-4b0f-bdda-46659ff594cb

		annotation PBI_FormatHint = {"isDecimal":true}

	measure VALOR = SUMX(SALES, SALES[MONTO_VENTA] / 1000000)
		formatString: 0.0
		lineageTag: a5228d78-28e1-4436-93ca-c573daa9edb8

	measure CB = SUMX(SALES, Sales[ContribucionBruta]/ 1000000)
		formatString: 0.0
		lineageTag: 8c4bd185-b5f0-4232-9bc7-a12b5b57dbb1

	measure Prom_3S = ```
			
			VAR Hoy = TODAY()
			VAR FinUltSemanaCompleta = Hoy - WEEKDAY(Hoy, 1)
			VAR Inicio3Semanas = FinUltSemanaCompleta - 20
			RETURN
			DIVIDE(
			    CALCULATE(
			        SUMX(
			            Sales, 
			            IF(
			                ISNUMBER(Sales[Fact]) && Sales[Fact] <> 0, 
			                DIVIDE(Sales[CANTIDAD], Sales[Fact], 0), 
			                0
			            )
			        ),
			        FILTER(
			            ALL(Sales[INVOICEDATE]),
			            Sales[INVOICEDATE] >= Inicio3Semanas
			                && Sales[INVOICEDATE] <= FinUltSemanaCompleta
			        )
			    ),
			    3
			)
			```
		formatString: 0
		lineageTag: 4b131d2d-13a2-45d6-9b81-f53b4e2a4c08

	measure Prom_3M = ```
			
			VAR Hoy = TODAY()
			VAR FinUltSemanaCompleta = Hoy - WEEKDAY(Hoy, 1)
			VAR Inicio13Semanas = FinUltSemanaCompleta - 90
			RETURN
			DIVIDE(
			    CALCULATE(
			        SUMX(
			            Sales, 
			            IF(
			                ISNUMBER(Sales[Fact]) && Sales[Fact] <> 0, 
			                DIVIDE(Sales[CANTIDAD], Sales[Fact], 0), 
			                0
			            )
			        ),
			        FILTER(
			            ALL(Sales[INVOICEDATE]),
			            Sales[INVOICEDATE] >= Inicio13Semanas
			                && Sales[INVOICEDATE] <= FinUltSemanaCompleta
			        )
			    ),
			    13
			)
			```
		formatString: 0
		lineageTag: 0ce0404b-d494-44f0-bacb-14e05e70e5c7

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Prom_3S_Valor =
			
			VAR Hoy = TODAY()
			VAR FinUltSemanaCompleta = Hoy - WEEKDAY(Hoy, 1)
			VAR Inicio3Semanas = FinUltSemanaCompleta - 20
			RETURN
			DIVIDE(
			    CALCULATE(
			        SUMX(Sales, Sales[MONTO_VENTA] / 1000000),
			        FILTER(
			            ALL(Sales[INVOICEDATE]),
			            Sales[INVOICEDATE] >= Inicio3Semanas
			                && Sales[INVOICEDATE] <= FinUltSemanaCompleta
			        )
			    ),
			    3
			)
		formatString: 0.0
		lineageTag: c187475e-3417-4a03-a567-d6ca35217447

	measure Prom_3M_Valor =
			
			VAR Hoy = TODAY()
			VAR FinUltSemanaCompleta = Hoy - WEEKDAY(Hoy, 1)
			VAR Inicio13Semanas = FinUltSemanaCompleta - 90
			RETURN
			DIVIDE(
			    CALCULATE(
			        SUMX(Sales, Sales[MONTO_VENTA] / 1000000),
			        FILTER(
			            ALL(Sales[INVOICEDATE]),
			            Sales[INVOICEDATE] >= Inicio13Semanas
			                && Sales[INVOICEDATE] <= FinUltSemanaCompleta
			        )
			    ),
			    13
			)
		formatString: 0.0
		lineageTag: 8a62019d-c1d9-4580-a312-7cf44c9e9e61

	measure MedidasAgrupadasCalculadas = ```
			
			SWITCH(
			    TRUE(),
			    SELECTEDVALUE(Grupos2[Medida]) = "5)VT-1", [QTY],
			    SELECTEDVALUE(Grupos2[Medida]) = "2)3S", [Prom_3S],
			    SELECTEDVALUE(Grupos2[Medida]) = "1)3M", [Prom_3M],
			    SELECTEDVALUE(Grupos2[Medida]) = "3)Est Meta Base", [Est_Base],
			    SELECTEDVALUE(Grupos2[Medida]) = "4)Est T0", [Est_T0],
			    SELECTEDVALUE(Grupos2[Medida]) = "5)VT-1.", [VALOR],
			    SELECTEDVALUE(Grupos2[Medida]) = "2)3S.", [Prom_3S_Valor],
			    SELECTEDVALUE(Grupos2[Medida]) = "1)3M.", [Prom_3M_Valor],
			    SELECTEDVALUE(Grupos2[Medida]) = "3)Est Meta Base.", [Valor_Estimada],
			    SELECTEDVALUE(Grupos2[Medida]) = "4)Est T0.", [Valor_Estimada_T0], 
			    SELECTEDVALUE(Grupos2[Medida]) = "6)%Val/Est Base", [NewVal],
			     SELECTEDVALUE(Grupos2[Medida]) = "CB T-1", [CB],
			  
			      
			   
			    BLANK()
			)
			
			
			```
		lineageTag: 33989370-3d80-4658-87d8-96987e05d82d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Valor_Estimada = ```
			
			 SUMX('CUBO INVENTARIOS', ('CUBO INVENTARIOS'[[Measures]].[Precio Promedio]]] * 'CUBO INVENTARIOS'[[Measures]].[Rot Diaria Total]]] * 7) / 1000000)
			```
		lineageTag: 71831371-e665-42fa-88f5-75c50db39e73

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Valor_Estimada_T0 = ```
			
			 SUMX('CUBO INVENTARIOS', (('CUBO INVENTARIOS'[[Measures]].[Precio Promedio]]] * 'CUBO INVENTARIOS'[[Measures]].[Rot Diaria Total]]] * 7)) * 'CUBO INVENTARIOS'[CRECIMIENTO.GROWTH] / 1000000)
			```
		lineageTag: 9b425caf-0356-45fa-a385-7a14f5982b6c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure NewVal = [VALOR] / [Valor_Estimada] * 100
		lineageTag: 4a772d39-245d-43d8-82be-c30d29e57d17

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Promedio CB' =
			
			CALCULATE(
			    AVERAGEX(VALUES(Sales[WEEK_INV]), [CB]),
			    ALLSELECTED(Sales[WEEK_INV])
			)
		lineageTag: 9e5c51da-deea-440e-91ae-a2d02be8326a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Promedio Venta' =
			
			CALCULATE(
			    AVERAGEX(VALUES(Sales[WEEK_INV]), [VALOR]),
			    ALLSELECTED(Sales[WEEK_INV])
			)
		lineageTag: ce76a6b1-787d-4cc8-995c-1c8efc641f13

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Promedio Cantidad' =
			
			CALCULATE(
			    AVERAGEX(VALUES(Sales[WEEK_INV]), [QTY]),
			    ALLSELECTED(Sales[WEEK_INV])
			)
		lineageTag: 5179859e-0a87-450c-8def-f8c1419c487d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Clientes Distintos Ult 4 Semanas' =
			
			CALCULATE(
			    DISTINCTCOUNT( Sales[CodCliente] ),
			    KEEPFILTERS( Sales[SEM] IN { "t-1", "t-2", "t-3", "t-4" } )
			)
		formatString: 0
		lineageTag: 3f6ab9f2-cdcb-4e7f-9420-25f042e39ef6

	measure Prom_3S_Esp = ```
			
			VAR Hoy = TODAY()
			VAR FinUltSemanaCompleta = Hoy - WEEKDAY ( Hoy, 1 )
			VAR Inicio3Semanas = FinUltSemanaCompleta - 20
			RETURN
			DIVIDE(
			    CALCULATE(
			        SUM ( Sales[Venta_Especial] ),
			        FILTER(
			            ALL ( Sales[INVOICEDATE] ),
			            Sales[INVOICEDATE] >= Inicio3Semanas
			                && Sales[INVOICEDATE] <= FinUltSemanaCompleta
			        )
			    ),
			    3
			)
			
			```
		formatString: #,0
		lineageTag: c392168f-5df4-48aa-97f2-98b21666664a

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Prom_3M_Esp = ```
			
			VAR Hoy = TODAY()
			VAR FinUltSemanaCompleta = Hoy - WEEKDAY ( Hoy, 1 )
			VAR Inicio13Semanas = FinUltSemanaCompleta - 90
			RETURN
			DIVIDE(
			    CALCULATE(
			        SUM ( Sales[Venta_Especial] ),
			        FILTER(
			            ALL ( Sales[INVOICEDATE] ),
			            Sales[INVOICEDATE] >= Inicio13Semanas
			                && Sales[INVOICEDATE] <= FinUltSemanaCompleta
			        )
			    ),
			    13
			)
			
			```
		formatString: #,0
		lineageTag: ff6f54ed-030a-4d56-b4a9-2d850a93675b

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'QTY Tar' = ```
			
			SUMX(
			    SALES, 
			    IF(
			        ISNUMBER(Sales[Fact Tar]) && Sales[Fact Tar] <> 0, 
			        DIVIDE(SALES[CANTIDAD], Sales[Fact Tar], 0), 
			        0
			    )
			)
			```
		formatString: 0.0
		lineageTag: 27c85e22-45b3-4871-babd-e538a409e512

	measure 'Cant Est Sem Und Esp' =
			
			SUMX(
			    SPECIAL_UNIT1,
			    [Est_Base] * SPECIAL_UNIT1[FACTOR]
			)
		formatString: #,0
		lineageTag: abe14d4f-fb34-446a-b09e-7aa4d30f35ae

		annotation PBI_FormatHint = {"isDecimal":true}

	column MONTO_VENTA
		dataType: double
		lineageTag: eeb2defb-5c9b-4939-aada-f7e59cf03c4e
		summarizeBy: sum
		sourceColumn: MONTO_VENTA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SEMANA
		dataType: int64
		formatString: 0
		lineageTag: 44cae86c-449f-4ef3-9ce3-70e5cff6a25a
		summarizeBy: sum
		sourceColumn: SEMANA

		annotation SummarizationSetBy = Automatic

	column ANNIO
		dataType: int64
		formatString: 0
		lineageTag: 9f32828d-0bd8-4414-b9e5-7322cafdc911
		summarizeBy: sum
		sourceColumn: ANNIO

		annotation SummarizationSetBy = Automatic

	column ITEMID
		dataType: string
		lineageTag: 2b8afeb6-b227-4642-8319-4ddb5ae8a783
		summarizeBy: none
		sourceColumn: ITEMID

		annotation SummarizationSetBy = Automatic

	column DATAAREAID
		dataType: string
		lineageTag: c727a6df-b788-4396-b9de-d5850f7269d3
		summarizeBy: none
		sourceColumn: DATAAREAID

		annotation SummarizationSetBy = Automatic

	column KEY_GEN
		dataType: string
		lineageTag: 5a90ebb8-49c8-4ffc-b590-3702e2a56cc0
		summarizeBy: none
		sourceColumn: KEY_GEN

		annotation SummarizationSetBy = Automatic

	column CANTIDAD
		dataType: double
		lineageTag: 18431247-3f80-4012-88b1-6aed861b4a04
		summarizeBy: sum
		sourceColumn: CANTIDAD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SEM = ```
			
			VAR Week = WEEKNUM(TODAY(), 1)
			VAR YearActual = YEAR(TODAY())
			VAR AnnioVenta = Sales[ANNIO]
			VAR SemanaVenta = Sales[SEMANA]
			
			-- Calcular semana absoluta (considerando año)
			VAR SemanaAbsolutaActual = YearActual * 52 + Week
			VAR SemanaAbsolutaVenta = AnnioVenta * 52 + SemanaVenta
			VAR Diferencia = SemanaAbsolutaActual - SemanaAbsolutaVenta
			
			RETURN 
			    SWITCH(
			        TRUE(),
			        Diferencia = 0, "t",
			        Diferencia = 1, "t-1",
			        Diferencia = 2, "t-2",
			        Diferencia = 3, "t-3",
			        Diferencia > 0, "t-" & Diferencia,
			        "future"
			    )
			```
		lineageTag: ff433109-6c35-4bbd-9fec-f447d9e50fe7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Fact = LOOKUPVALUE(Unidades[Und X Cajas], Unidades[Dim Conversiones.Articulo], SALES[ITEMID])
		lineageTag: 18544f64-2e1a-41ff-8b26-f665f45f8d4f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date = LOOKUPVALUE(Dates2[Fecha], Dates2[Semana], SALES[SEM])
		formatString: dd/mm/yy
		lineageTag: 365a61c9-e7c4-4dc5-a0f9-820cd74f8bc8
		summarizeBy: none

		variation Variación
			isDefault
			relationship: d729bfa2-0ba4-4764-9016-15c63ba87e36
			defaultHierarchy: LocalDateTable_898e7e83-0bd9-4c1a-af02-939f8af875a3.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column WEEK = CONCATENATE(SALES[SEM],CONCATENATE(" (",CONCATENATE(SALES[SEMANA],")")))
		lineageTag: ec3af7bf-4b54-4fb0-b717-77187ab938f8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ContribucionBruta
		dataType: double
		lineageTag: 29aa98a5-e276-40e1-b0bc-fd855e6c8887
		summarizeBy: sum
		sourceColumn: ContribucionBruta

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ID =
			SWITCH(
			    TRUE,
			    Sales[SEM] = "t-1", 1,
			    Sales[SEM] = "t-2", 2,
			    Sales[SEM] = "t-3", 3,
			    Sales[SEM] = "t-4", 4,
			    Sales[SEM] = "t-5", 5,
			    Sales[SEM] = "t-6", 6,
			    Sales[SEM] = "t-7", 7,
			    Sales[SEM] = "t-8", 8,
			    Sales[SEM] = "t-9", 9,
			    Sales[SEM] = "t-10", 10,
			    Sales[SEM] = "t-11", 11,
			    Sales[SEM] = "t-12", 12,
			    Sales[SEM] = "t-13", 13,
			    0)
		formatString: 0
		lineageTag: 6a5dec23-c8e1-4572-81ac-39846797df41
		summarizeBy: count

		annotation SummarizationSetBy = Automatic

	column CodCliente
		dataType: string
		lineageTag: 41624ade-e1d5-4b3c-a8eb-fdb6c93ca4a1
		summarizeBy: none
		sourceColumn: CodCliente

		annotation SummarizationSetBy = Automatic

	column WEEK_INV = CONCATENATE(CONCATENATE(" (",CONCATENATE(SALES[SEMANA],")")),SALES[SEM])
		lineageTag: 35881421-8ed7-44f8-952b-fede91191977
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Venta_Especial
		dataType: double
		lineageTag: 6fe99d1e-084a-4de8-b9c9-e7744f737191
		summarizeBy: sum
		sourceColumn: Venta_Especial

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UNIDADESPECIAL
		dataType: string
		lineageTag: 3ed86449-dcd1-444e-a853-a539ba0da5c2
		summarizeBy: none
		sourceColumn: UNIDADESPECIAL

		annotation SummarizationSetBy = Automatic

	column INVOICEDATE
		dataType: dateTime
		formatString: General Date
		lineageTag: d59ddd61-1d5b-439c-9499-1048275893a7
		summarizeBy: none
		sourceColumn: INVOICEDATE

		variation Variación
			isDefault
			relationship: 52c2dda6-2b21-4bcd-b03d-da7a70974863
			defaultHierarchy: LocalDateTable_674a7c26-6bfc-40cd-9d1b-aae20aaba826.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Fact Tar' = LOOKUPVALUE(CATALOGO_PBI_SALES[FACTOR_TARIMA], CATALOGO_PBI_SALES[ITEMID], SALES[ITEMID])
		lineageTag: bb65d3bc-a978-4014-a2bf-fb573cdd7747
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FACTOR_UND_ESP
		dataType: double
		lineageTag: da606c41-b8e3-4dd5-a3b3-3e6f9c6d3adc
		summarizeBy: sum
		sourceColumn: FACTOR_UND_ESP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Vendedor
		dataType: string
		lineageTag: c6ecde88-15d1-4bb5-8dff-7130b97626ba
		summarizeBy: none
		sourceColumn: Vendedor

		annotation SummarizationSetBy = Automatic

	column key_vendedor
		dataType: string
		lineageTag: f6f05f7e-15fa-4da8-8070-ba40c519d15b
		summarizeBy: none
		sourceColumn: key_vendedor

		annotation SummarizationSetBy = Automatic

	column Fecha_TEST = LOOKUPVALUE(Dates2_TEST[Fecha], Dates2_TEST[Semana], SALES[SEM])
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: edbd49ba-1945-416f-a4eb-2b21a427823b
		summarizeBy: none

		variation Variación
			isDefault
			relationship: fecdc24e-feb1-4ca3-a38d-326a207f78ba
			defaultHierarchy: LocalDateTable_afcb6ebb-1ced-4434-a072-28f85805e86a.'Date Hierarchy'

	column Semana_TEST = COALESCE(LOOKUPVALUE(Dates2_TEST[Semana], Dates2_TEST[Semana], SALES[SEM]), "T-13")
		dataType: string
		lineageTag: a8d5c9f8-0816-42d7-90a4-c3a973e2538b
		summarizeBy: none
		sortByColumn: Orden_TEST

	column Orden_TEST = COALESCE(LOOKUPVALUE(Dates2_TEST[Orden], Dates2_TEST[Semana], SALES[SEM]), 13)
		dataType: int64
		isHidden
		lineageTag: 43c68257-c9e8-4679-93f0-7cee7f5b3961
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Jerarquía'
		lineageTag: 6e6176dc-6bf3-4a0c-815f-00323483300b

		level Fecha
			lineageTag: f2fbe2e4-5257-4b0b-be4f-d47039a36e15
			column: Date

	hierarchy 'Date Jerarquía Descendente'
		lineageTag: 6218065f-b5cc-4ef6-9379-f1c789295251

		level Semana
			lineageTag: 08b90c31-e6eb-4bce-aa56-a6fff3f4a79d
			column: Semana_TEST

		level Fecha
			lineageTag: b4d5ede5-7f7b-4ff0-a4e6-2b25bf9c3d70
			column: Fecha_TEST

	partition Sales = m
		mode: import
		source =
				let
				    Source = Sql.Database("SJODB003", "GIAX2012_PROD", [Query="WITH COGS AS (#(lf)    SELECT#(lf)        DATAAREAID,#(lf)        INVOICEID,#(lf)        INVENTTRANSID,#(lf)        SUM(COGS) AS Total_COGS#(lf)    FROM#(lf)        CostOfGoodsSold#(lf)    GROUP BY#(lf)        DATAAREAID,#(lf)        INVOICEID,#(lf)        INVENTTRANSID#(lf))#(lf)#(lf)SELECT#(lf)    SUM(T1.LINEAMOUNTMST) AS MONTO_VENTA,#(lf)    DATEPART(WEEK, T1.INVOICEDATE) AS SEMANA,#(lf)    DATEPART(YEAR, T1.INVOICEDATE) AS ANNIO,#(lf)    T1.ITEMID,#(lf)    T1.DATAAREAID,#(lf)    T1.DATAAREAID + T1.ITEMID AS KEY_GEN,#(lf)    SUM(T1.INVENTQTY) AS CANTIDAD,#(lf)    SUM(T1.LINEAMOUNTMST - ISNULL(C.Total_COGS, 0)) AS ContribucionBruta,#(lf)#(tab)t2.INVOICEACCOUNT as CodCliente,#(lf)#(tab)SUM(T1.INVENTQTY * T3.FACTOR) AS Venta_Especial,#(lf)#(tab)T3.SYMBOL AS UNIDADESPECIAL,#(lf)#(tab)MAX(T3.FACTOR) AS FACTOR_UND_ESP,#(lf)#(tab)T1.INVOICEDATE,#(lf)#(tab)CASE #(lf)            WHEN ISNULL(T50.ROLESPECIFICID, '') = '' #(lf)            THEN T51.ROLESPECIFICID #(lf)            ELSE T50.ROLESPECIFICID #(lf)        END AS Vendedor#(lf)FROM#(lf)    CUSTINVOICETRANS T1#(lf)LEFT JOIN CUSTINVOICEJOUR T2 ON T2.INVOICEID=T1.INVOICEID AND T2.DATAAREAID=T1.DATAAREAID AND T2.PARTITION=T1.PARTITION and t1.INVOICEDATE=t2.INVOICEDATE and t1.SALESID=t2.SALESID#(lf)LEFT JOIN#(lf)    COGS C ON T1.DATAAREAID = C.DATAAREAID#(lf)               AND T1.INVOICEID = C.INVOICEID#(lf)               AND T1.INVENTTRANSID = C.INVENTTRANSID#(lf)LEFT OUTER JOIN SPECIAL_UNIT1 T3 ON T3.DISPLAYPRODUCTNUMBER = T1.ITEMID#(lf)LEFT JOIN RoleSpecificAddressGenPBI T50 WITH (NOLOCK)#(lf)        ON T50.REFRECID = T2.ADDRESSREFRECID#(lf)        AND T50.DATAAREAID = T2.DATAAREAID#(lf)        AND T50.ROLEID LIKE '%Vendedor%' #(lf)LEFT JOIN RoleSpecificCustGenPBI T51 WITH (NOLOCK)#(lf)        ON T51.ACCOUNTNUM = T2.INVOICEACCOUNT #(lf)        AND T51.DATAAREAID = T2.DATAAREAID#(lf)        AND T51.ROLEID LIKE '%Vendedor%' #(lf)WHERE#(lf)    T1.DATAAREAID IN ('CMER', 'FMCM')#(lf)    AND T1.INVOICEDATE >= DATEADD(WEEK, -14, GETDATE())#(lf)    AND T1.PARTITION = 5637144576#(lf)GROUP BY#(lf)    DATEPART(WEEK, T1.INVOICEDATE),#(lf)    DATEPART(YEAR, T1.INVOICEDATE),#(lf)    T1.ITEMID,#(lf)    T1.DATAAREAID,#(lf)#(tab)t2.INVOICEACCOUNT,#(lf)#(tab)T3.SYMBOL,#(lf)#(tab)T1.INVOICEDATE,#(lf)#(tab)T50.ROLESPECIFICID,#(lf)#(tab)T51.ROLESPECIFICID", MultiSubnetFailover=true]),
				    #"Valor reemplazado" = Table.ReplaceValue(Source,null,"ND",Replacer.ReplaceValue,{"Vendedor"}),
				    #"Personalizada agregada" = Table.AddColumn(#"Valor reemplazado", "key_vendedor", each [DATAAREAID]&[Vendedor])
				in
				    #"Personalizada agregada"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

