table vPURCHDESCARGASBI
	lineageTag: 6f2eb6ab-0d63-4361-86ae-d54039ce27ef

	column CREATEDDATETIME
		dataType: dateTime
		formatString: dd-mmm-yy
		lineageTag: 6ef3e428-baac-473c-9005-7e89f6729402
		summarizeBy: none
		sourceColumn: CREATEDDATETIME

		variation Variación
			isDefault
			relationship: 1752e707-cc34-492d-a7cf-adb9e86f7db0
			defaultHierarchy: LocalDateTable_c236a247-e413-4aeb-8fda-888e7c0cfc97.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column PURCHID
		dataType: string
		lineageTag: 9b123676-a655-479e-ad83-dbbf33307cf1
		summarizeBy: none
		sourceColumn: PURCHID

		annotation SummarizationSetBy = Automatic

	column PURCHNAME
		dataType: string
		lineageTag: 6e0a6f1d-1c55-45c6-9084-300aa204f020
		summarizeBy: none
		sourceColumn: PURCHNAME

		annotation SummarizationSetBy = Automatic

	column ORDERACCOUNT
		dataType: string
		lineageTag: 2287ac1e-e5d9-4f87-9787-ac0404c6c851
		summarizeBy: none
		sourceColumn: ORDERACCOUNT

		annotation SummarizationSetBy = Automatic

	column VENDGROUP
		dataType: string
		lineageTag: ac0952cf-7596-4baf-af35-625cf3483429
		summarizeBy: none
		sourceColumn: VENDGROUP

		annotation SummarizationSetBy = Automatic

	column SIT_DUA
		dataType: string
		lineageTag: 6ecf3728-6843-43f1-b5e0-f7454126a263
		summarizeBy: none
		sourceColumn: SIT_DUA

		annotation SummarizationSetBy = Automatic

	column SIT_FREEDAYS
		dataType: int64
		formatString: 0
		lineageTag: bb10e89f-a1f7-46b4-8418-3ba5cbfe0fb3
		summarizeBy: sum
		sourceColumn: SIT_FREEDAYS

		annotation SummarizationSetBy = Automatic

	column SIT_CONTAINERS
		dataType: string
		lineageTag: e3b298ab-0ab2-45be-a8e6-41e2d236e0df
		summarizeBy: none
		sourceColumn: SIT_CONTAINERS

		annotation SummarizationSetBy = Automatic

	column DATAAREAID
		dataType: string
		lineageTag: 283c43c0-79f4-4569-8031-facc9e316def
		summarizeBy: none
		sourceColumn: DATAAREAID

		annotation SummarizationSetBy = Automatic

	column PORT
		dataType: string
		lineageTag: f71ecc15-a7a1-4a0c-a5eb-e2fbbb5f531d
		summarizeBy: none
		sourceColumn: PORT

		annotation SummarizationSetBy = Automatic

	column TRANSPORT
		dataType: string
		lineageTag: 4d927a37-3d50-450f-8464-2798765b4681
		summarizeBy: none
		sourceColumn: TRANSPORT

		annotation SummarizationSetBy = Automatic

	column SIT_AIRWAYBILL
		dataType: string
		lineageTag: 3c750fc8-8946-4981-b3e2-196a22c4c0c4
		summarizeBy: none
		sourceColumn: SIT_AIRWAYBILL

		annotation SummarizationSetBy = Automatic

	column 'PURCHID - Copia'
		dataType: string
		lineageTag: 0b21e522-0a39-4a28-9f62-c34a90425640
		summarizeBy: none
		sourceColumn: PURCHID - Copia

		annotation SummarizationSetBy = Automatic

	column PRODUCTNAME
		dataType: string
		lineageTag: 530c90f5-25f9-48ba-b96d-1df0275c1766
		summarizeBy: none
		sourceColumn: PRODUCTNAME

		annotation SummarizationSetBy = Automatic

	partition vPURCHDESCARGASBI = m
		mode: import
		source =
				let
				    Origen = Sql.Database("SJODB003", "GIAX2012_PROD"),
				    dbo_SYSMODEL = Origen{[Schema="dbo",Item="vPURCHDESCARGASBI"]}[Data],
				    #"Columna duplicada" = Table.DuplicateColumn(dbo_SYSMODEL, "PURCHID", "PURCHID - Copia"),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Columna duplicada","OC-00","",Replacer.ReplaceText,{"PURCHID - Copia"}),
				    #"Duplicados quitados" = Table.Distinct(#"Valor reemplazado", {"PURCHID"})
				in
				    #"Duplicados quitados"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

