table COTIZACIONES
	lineageTag: 19bfc1e0-a9d8-4252-ab37-2cdd3baf09db

	measure Minimo = MIN(COTIZACIONES[MONTO])
		lineageTag: fd962be6-9c52-46b7-b3e7-87b00d820953

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EMPRESA
		dataType: string
		lineageTag: d98f6791-d556-4fc4-a6a1-2a1c63e18390
		summarizeBy: none
		sourceColumn: EMPRESA

		annotation SummarizationSetBy = Automatic

	column PRODUCTO
		dataType: string
		lineageTag: 53c984fc-697a-4369-a5b3-895fe24707f5
		summarizeBy: none
		sourceColumn: PRODUCTO

		annotation SummarizationSetBy = Automatic

	column PROVEEDOR
		dataType: string
		lineageTag: 2d20c203-dd3b-462e-9f27-047edbe960a6
		summarizeBy: none
		sourceColumn: PROVEEDOR

		annotation SummarizationSetBy = Automatic

	column DESDE
		dataType: dateTime
		formatString: DD-MM-YYYY
		lineageTag: d2e4eca5-c5d0-4903-a596-4628ea5c2497
		summarizeBy: none
		sourceColumn: DESDE

		variation Variación
			isDefault
			relationship: 738abbc6-8032-4cb0-b278-cbaeea2d7807
			defaultHierarchy: LocalDateTable_9e50370e-64e8-47b3-a705-a4a59d83445d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column HASTA
		dataType: dateTime
		formatString: DD-MM-YYYY
		lineageTag: a746de63-c526-4aa9-87ed-b329dd0710a3
		summarizeBy: none
		sourceColumn: HASTA

		variation Variación
			isDefault
			relationship: 20129bb6-236a-4d52-900b-489dd033fd2d
			defaultHierarchy: LocalDateTable_108dc081-1044-4158-9cfa-710d96d4e0fc.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column UNIDAD
		dataType: string
		lineageTag: def6b715-604c-45cb-ad44-3d8376950df8
		summarizeBy: none
		sourceColumn: UNIDAD

		annotation SummarizationSetBy = Automatic

	column MONEDA
		dataType: string
		lineageTag: ee8dcd72-7dfa-45b0-9354-1af734830db1
		summarizeBy: none
		sourceColumn: MONEDA

		annotation SummarizationSetBy = Automatic

	column MONTO
		dataType: double
		lineageTag: 5fe4c482-4eaf-4cd4-9b8d-a05466154cf3
		summarizeBy: sum
		sourceColumn: MONTO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column KEY
		dataType: string
		lineageTag: 353da18a-b238-4c0e-ad25-1ec9eafd7d37
		summarizeBy: none
		sourceColumn: KEY

		annotation SummarizationSetBy = Automatic

	column KEY_1
		dataType: string
		lineageTag: 0643331b-a025-41e4-9620-dcc7f4836275
		summarizeBy: none
		sourceColumn: KEY_1

		annotation SummarizationSetBy = Automatic

	column CONCAT_UND = CONCATENATE(COTIZACIONES[MONEDA], CONCATENATE(" ", COTIZACIONES[UNIDAD]))
		lineageTag: 24b6b7f0-eee4-41b0-a558-ac3ca932786c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	hierarchy 'DESDE Jerarquía'
		lineageTag: 0817ce6d-6d8f-4ac0-aae6-0cd04a6d5a48

		level 'Cotización Vigente Desde'
			lineageTag: 8c90ac34-47fe-44d7-9608-8d3ada58f34b
			column: DESDE

	hierarchy 'HASTA Jerarquía'
		lineageTag: 77130a65-84a4-40ef-8350-8569b65a3bf4

		level 'Cotización Vigente Hasta'
			lineageTag: 22568441-d8e9-4e59-882b-614b3bcd8b5e
			column: HASTA

	partition COTIZACIONES = m
		mode: import
		source =
				let
				    Origen = Sql.Database("SJODB002", "GIAX2012_PROD", [Query="SELECT DISTINCT DATAAREAID AS EMPRESA,#(lf)ITEMRELATION AS PRODUCTO,#(lf)ACCOUNTRELATION AS PROVEEDOR,#(lf)FROMDATE AS DESDE,#(lf)TODATE AS HASTA,#(lf)UNITID AS UNIDAD,#(lf)CURRENCY AS MONEDA,#(lf)AMOUNT AS MONTO#(lf)FROM PRICEDISCTABLE#(lf)WHERE #(lf)RELATION = 0 #(lf)AND (TODATE = ('1900-01-01 00:00:00.000') OR TODATE > GETDATE())#(lf)AND DATAAREAID = 'CMER'#(lf)AND MODULE = 2 #(lf)AND PARTITION = 5637144576", MultiSubnetFailover=true]),
				    #"Personalizada agregada" = Table.AddColumn(Origen, "KEY", each [EMPRESA]&[PRODUCTO]),
				    #"Personalizada agregada1" = Table.AddColumn(#"Personalizada agregada", "KEY_1", each [EMPRESA]&[PROVEEDOR])
				in
				    #"Personalizada agregada1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

