table Dates
	lineageTag: 23f69bee-dec0-405f-839c-89aad75d341d

	column Semana
		dataType: string
		lineageTag: 68004ad2-88bd-414a-8603-077967070e7d
		summarizeBy: none
		sourceColumn: Semana

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 24080bdc-c288-4257-a77a-f3dd9b23fc6f
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: a12c176a-5acf-449e-bbe0-d7bd4816a42a
			defaultHierarchy: LocalDateTable_7c07443e-a12e-4c91-a15f-49dc32c9e03c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Dates = m
		mode: import
		source =
				let
				    Origen = Sql.Database("SJODB002", "GIAX2012_PROD", [Query="SELECT #(lf)DATEADD(day, 8 - DATEPART(weekday, getdate()), getdate()) AS ""T+1"",#(lf)DATEADD(day, 15 - DATEPART(weekday, getdate()), getdate()) AS ""T+2"",#(lf)DATEADD(day, 22 - DATEPART(weekday, getdate()), getdate()) AS ""T+3"",#(lf)DATEADD(day, 29 - DATEPART(weekday, getdate()), getdate()) AS ""T+4"",#(lf)DATEADD(day, 36 - DATEPART(weekday, getdate()), getdate()) AS ""T+5"",#(lf)DATEADD(day, 43 - DATEPART(weekday, getdate()), getdate()) AS ""T+6"",#(lf)DATEADD(day, 50 - DATEPART(weekday, getdate()), getdate()) AS ""T+7"",#(lf)DATEADD(day, 57 - DATEPART(weekday, getdate()), getdate()) AS ""T+8"",#(lf)DATEADD(day, 64 - DATEPART(weekday, getdate()), getdate()) AS ""T+9"",#(lf)DATEADD(day, 71 - DATEPART(weekday, getdate()), getdate()) AS ""T+10"",#(lf)DATEADD(day, 78 - DATEPART(weekday, getdate()), getdate()) AS ""T+11"",#(lf)DATEADD(day, 85 - DATEPART(weekday, getdate()), getdate()) AS ""T+12"",#(lf)DATEADD(day, 92 - DATEPART(weekday, getdate()), getdate()) AS ""T+13"",#(lf)DATEADD(day, 99 - DATEPART(weekday, getdate()), getdate()) AS ""T+14"",#(lf)DATEADD(day, 106 - DATEPART(weekday, getdate()), getdate()) AS ""T+15"",#(lf)DATEADD(day, 113 - DATEPART(weekday, getdate()), getdate()) AS ""T+16"",#(lf)DATEADD(day, 120 - DATEPART(weekday, getdate()), getdate()) AS ""T+17"",#(lf)DATEADD(day, 127 - DATEPART(weekday, getdate()), getdate()) AS ""T+18"",#(lf)DATEADD(day, 134 - DATEPART(weekday, getdate()), getdate()) AS ""T+19"",#(lf)DATEADD(day, 141 - DATEPART(weekday, getdate()), getdate()) AS ""T+20"",#(lf)DATEADD(day, 148 - DATEPART(weekday, getdate()), getdate()) AS ""T+21"",#(lf)DATEADD(day, 155 - DATEPART(weekday, getdate()), getdate()) AS ""T+22"",#(lf)DATEADD(day, 162 - DATEPART(weekday, getdate()), getdate()) AS ""T+23"",#(lf)DATEADD(day, 169 - DATEPART(weekday, getdate()), getdate()) AS ""T+24"",#(lf)DATEADD(day, 176 - DATEPART(weekday, getdate()), getdate()) AS ""T+25"",#(lf)DATEADD(day, 183 - DATEPART(weekday, getdate()), getdate()) AS ""T+26"",#(lf)DATEADD(day, 190 - DATEPART(weekday, getdate()), getdate()) AS ""T+27"",#(lf)DATEADD(day, 197 - DATEPART(weekday, getdate()), getdate()) AS ""T+28"",#(lf)DATEADD(day, 204 - DATEPART(weekday, getdate()), getdate()) AS ""T+29"",#(lf)DATEADD(day, 211 - DATEPART(weekday, getdate()), getdate()) AS ""T+30"",#(lf)DATEADD(day, 218 - DATEPART(weekday, getdate()), getdate()) AS ""T+31"",#(lf)DATEADD(day, 225 - DATEPART(weekday, getdate()), getdate()) AS ""T+32"",#(lf)DATEADD(day, 232 - DATEPART(weekday, getdate()), getdate()) AS ""T+33"",#(lf)DATEADD(day, 239 - DATEPART(weekday, getdate()), getdate()) AS ""T+34"",#(lf)DATEADD(day, 246 - DATEPART(weekday, getdate()), getdate()) AS ""T+35"",#(lf)DATEADD(day, 253 - DATEPART(weekday, getdate()), getdate()) AS ""T+36""", MultiSubnetFailover=true]),
				    #"Demoted Headers" = Table.DemoteHeaders(Origen),
				    #"Changed Type" = Table.TransformColumnTypes(#"Demoted Headers",{{"Column1", type any}, {"Column2", type any}, {"Column3", type any}, {"Column4", type any}, {"Column5", type any}, {"Column6", type any}, {"Column7", type any}, {"Column8", type any}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}, {"Column13", type any}, {"Column14", type any}, {"Column15", type any}, {"Column16", type any}, {"Column17", type any}, {"Column18", type any}, {"Column19", type any}, {"Column20", type any}, {"Column21", type any}, {"Column22", type any}, {"Column23", type any}, {"Column24", type any}, {"Column25", type any}, {"Column26", type any}, {"Column27", type any}, {"Column28", type any}, {"Column29", type any}, {"Column30", type any}, {"Column31", type any}, {"Column32", type any}, {"Column33", type any}, {"Column34", type any}, {"Column35", type any}, {"Column36", type any}}),
				    #"Transposed Table" = Table.Transpose(#"Changed Type"),
				    #"Renamed Columns" = Table.RenameColumns(#"Transposed Table",{{"Column1", "Semana"}, {"Column2", "Fecha"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"Fecha", type date}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

