table RECEPCIONES
	lineageTag: ec95da7d-e155-4513-acf3-0d2f914ef0ec

	column PO
		dataType: string
		lineageTag: 128093a8-c3d1-4ff0-88c7-bb58dce735b6
		summarizeBy: none
		sourceColumn: PO

		annotation SummarizationSetBy = Automatic

	column RECEPCION_PRODUCTO
		dataType: string
		lineageTag: b36e7ca1-0712-4b2a-ab42-805f7ea9dfaf
		summarizeBy: none
		sourceColumn: RECEPCION_PRODUCTO

		annotation SummarizationSetBy = Automatic

	column CANT_RECIBIDO
		dataType: double
		formatString: #,0
		lineageTag: 6766d385-4dcc-4d9e-9413-b248db81ca37
		summarizeBy: sum
		sourceColumn: CANT_RECIBIDO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column UNIDAD_RECIBIDO
		dataType: string
		lineageTag: c7e24cf8-ca3a-4826-954c-af4a52f3a030
		summarizeBy: none
		sourceColumn: UNIDAD_RECIBIDO

		annotation SummarizationSetBy = Automatic

	column FECHA
		dataType: dateTime
		formatString: DD/MM/YY
		lineageTag: 87e1134e-a280-4d72-8b50-8873390ea6f7
		summarizeBy: none
		sourceColumn: FECHA

		variation Variación
			isDefault
			relationship: 4f29a467-e4ca-44a1-9fc5-93f05959c136
			defaultHierarchy: LocalDateTable_1ca8f148-28b0-46f5-bf00-fccc708b73a0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column KEY_RECEP
		dataType: string
		lineageTag: d7105471-9cbb-4f3b-9ca5-3909169208bc
		summarizeBy: none
		sourceColumn: KEY_RECEP

		annotation SummarizationSetBy = Automatic

	column ITEMID
		dataType: string
		lineageTag: 7772b8c6-3c6c-4652-b778-308711d037f8
		summarizeBy: none
		sourceColumn: ITEMID

		annotation SummarizationSetBy = Automatic

	hierarchy 'FECHA Jerarquía'
		lineageTag: 58917690-0a27-4160-99fe-19b1675c2f90

		level 'Fecha Recep'
			lineageTag: 64f40524-a42c-4417-adc3-8bb1caf65e36
			column: FECHA

	partition RECEPCIONES = m
		mode: import
		source =
				let
				    Origen = Sql.Database("SJODB002", "GIAX2012_PROD", [Query="SELECT T1.ORIGPURCHID AS PO, T1.PACKINGSLIPID AS RECEPCION_PRODUCTO, SUM(T1.QTY) AS CANT_RECIBIDO, T1.PURCHUNIT AS UNIDAD_RECIBIDO, T1.DELIVERYDATE AS FECHA, T1.ITEMID#(lf)FROM VendPackingSlipTrans T1 INNER JOIN#(lf)PURCHTABLE T2 ON T2.DATAAREAID = T1.DATAAREAID AND T1.ORIGPURCHID = T2.PURCHID#(lf)WHERE T2.DATAAREAID = 'CMER' AND T1.DELIVERYDATE > DATEADD(MONTH,-24,GETDATE()) AND QTY <> 0 #(lf)GROUP BY T1.ORIGPURCHID, T1.PACKINGSLIPID, T1.PURCHUNIT, T1.DELIVERYDATE, T1.ITEMID", MultiSubnetFailover=true]),
				    #"Personalizada agregada" = Table.AddColumn(Origen, "KEY_RECEP", each [PO] & [UNIDAD_RECIBIDO] & [ITEMID])
				in
				    #"Personalizada agregada"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

