table lugar_pais
	lineageTag: 72ac65a6-d5bf-4fd9-9799-ec756f7c75be

	column id_lugar_pais
		dataType: int64
		formatString: 0
		lineageTag: 32974075-3d27-4da5-805c-b84765255c0a
		summarizeBy: sum
		sourceColumn: id_lugar_pais

		annotation SummarizationSetBy = Automatic

	column id_region
		dataType: int64
		formatString: 0
		lineageTag: f003b074-d063-402c-86ae-1461a6653e78
		summarizeBy: none
		sourceColumn: id_region

		annotation SummarizationSetBy = Automatic

	column cod_pais
		dataType: int64
		formatString: 0
		lineageTag: 9bfe8160-d25b-45b4-9a73-aff3cded6c7b
		summarizeBy: sum
		sourceColumn: cod_pais

		annotation SummarizationSetBy = Automatic

	column nombre_pais
		dataType: string
		lineageTag: d822702f-b43b-4dc5-992c-803a3d01e4d0
		summarizeBy: none
		sourceColumn: nombre_pais

		annotation SummarizationSetBy = Automatic

	column 'regiones.nombre_region'
		dataType: string
		lineageTag: d5da9b75-951b-4f59-bccf-f4b4b3dbec5d
		summarizeBy: none
		sourceColumn: regiones.nombre_region

		annotation SummarizationSetBy = Automatic

	column 'COUNTRY_CODE.Code'
		dataType: string
		lineageTag: e7205989-e856-47b3-9f88-2e4e7703733f
		summarizeBy: none
		sourceColumn: COUNTRY_CODE.Code

		annotation SummarizationSetBy = Automatic

	partition lugar_pais = m
		mode: import
		source =
				let
				    Source = Json.Document(Web.Contents("http://sjoiis01:8012/ajuste_sistema/regiones/lugar_pais")),
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"id_lugar_pais", "id_region", "cod_pais", "nombre_pais", "id_lugar", "nombre_lugar"}, {"id_lugar_pais", "id_region", "cod_pais", "nombre_pais", "id_lugar", "nombre_lugar"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1",{{"id_lugar_pais", Int64.Type}, {"id_region", Int64.Type}, {"cod_pais", Int64.Type}, {"nombre_pais", type text}, {"id_lugar", type any}, {"nombre_lugar", type any}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"id_region"}, regiones, {"id_region"}, "regiones", JoinKind.LeftOuter),
				    #"Expanded regiones" = Table.ExpandTableColumn(#"Merged Queries", "regiones", {"nombre_region"}, {"regiones.nombre_region"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded regiones",{"nombre_lugar", "id_lugar"}),
				    #"Consultas combinadas" = Table.NestedJoin(#"Removed Columns", {"nombre_pais"}, COUNTRY_CODE, {"Country"}, "COUNTRY_CODE", JoinKind.LeftOuter),
				    #"Se expandió COUNTRY_CODE" = Table.ExpandTableColumn(#"Consultas combinadas", "COUNTRY_CODE", {"Code"}, {"COUNTRY_CODE.Code"})
				in
				    #"Se expandió COUNTRY_CODE"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

